### PR TITLE
Optional: Merge for collaboration and great justice

### PR DESCRIPTION
**Pull request by pdeona**
Made some refactors ahead of beginning my work on building out the API endpoints. Breaking changes included. If you are open to collaborating on this gem let me know, I was going to start my own before I found this.

### CODE REVIEW

**Comment by alexander-clark** [comment]
@pdeona I apologize for taking so long to respond on this. I'd definitely be interested in collaborating if you're still open to it.

**Comment by pdeona** [comment]
@alexander-clark no problem at all. I closed the PR because it seemed like it had diverged pretty far from the original fork. I'll reopen if you want to merge and I will add you as a collaborator to my fork so you don't have to worry about breaking changes to anything you've built with this version.

**Comment by alexander-clark** [comment]
@pdeona I don't have any production code relying on this yet. My dev environment is pointed at a specific release, so I can merge this as is. Then I'll make any necessary changes in another PR before issuing another release.

I'd be happy to have your input on future PRs to minimize the possibility of breaking changes for you or other users of the gem. And of course I'd welcome PRs as well. I'll try to be a bit more responsive in the future ;)

**Comment by pdeona** [comment]
I'm building this for an API that we rely on in production now, but the gem hasnt been added into the API yet. I'm going to start building new features in branches now that a good number of methods have been built, just in case anyone is using the gem, so I can just keep building on my fork and submit PRs on release-ready builds when I merge new features in. 

right now I am working on the following:
```
Scheduling:
- client.reschedule_visit(visit: <Visit>, patient: <Patient>)
- client.modify_visit(visit: <Visit>, patient: <Patient>)
- client.visit_no_show(visit: <Visit>, patient: <Patient>)
Orders:
- client.add_order(order: <Order>, patient: <Patient>, *visit: <Visit>)
- client.update_order(order: <Order>, patient: <Patient>, *visit: <Visit>)
- client.cancel_order(order: <Order>, patient: <Patient>, *visit: <Visit>)
- client.add_orders(orders[]: <Order>, patient: <Patient>, *visit: <Visit)
```
based on the [Scheduling](https://developer.redoxengine.com/data-models/Scheduling.html) & [Orders](https://developer.redoxengine.com/data-models/Order.html) data models.
I also plan on adding `.to_h` and `.to_json` methods to the Patient and Visit classes for more usability and to eventually serialize all responses into their corresponding class. I also need to build classes for the rest of the data models like I have for Patient and Visit to do that. so I welcome any contribution to the other data models, or any proposed improvements for the data model classes. I want to add in a way to pass in the existing client to enable methods like `<Patient>.add_visit(visit: <Visit>)` but I haven't started that either. Let me know your thoughts.

**Comment by pdeona** [comment]
going to push today with the rest of the Scheduling endpoints and tests. I'm going to add instructions to the README for getting circleCI passing as well, the issue I'm having now is just editing the test inputs to be valid currently since they are testing against the live Athena Sandbox. alternatively putting source/destination info for the Redox Dev EMR should allow all tests to pass, unfortunately this endpoint doesn't actually validate a lot of input, so i try to avoid using it to test the methods where possible. @alexander-clark

**Pull request merged**
